apiVersion: v1
kind: Service
metadata:
  namespace: BookService
  labels:
    app: BookService
  name: BookService
spec:
  ports:
  
    - protocol: TCP
      port: 4500
      targetPort: 4500
   
  selector:
    app: BookService
  type: ClusterIP
